version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 5005:5005
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.19.3"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    tty: true
    stdin_open: true
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data